# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: beddd3a2d97b5fd318af0a4f730575b672ad35c20d635c1527623b0baa54352c0046d45b802abac50d4d1949868d6b045dcd3da0bdb846a94776e65f6858ecc8

test:
  secret_key_base: 00857d13624e2b9d442142245c7750681766a5211febbdae2768e152536ade973b4c6810b840b232b7c6b0a9f59958aa9bbcce9b1ad7d79268d1876cf5dece8e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
